agency/urls.py
from django.urls import path

from agency.views import (
    index,
    NewspaperListView,
    NewspaperCreateView,
    TopicDetailView,
    TopicCreateView,
    TopicDeleteView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    newspaper_detail_view,
    NewspaperDeleteView,
    NewspaperUpdateView,
    redactor_detail_view,
)

urlpatterns = [
    path("", index, name="index"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", newspaper_detail_view, name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("topics/<int:pk>/", TopicDetailView.as_view(), name="topic-detail"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", redactor_detail_view, name="redactor-detail"),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactors/<int:pk>/update",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agency/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from newspaper_agency import settings


class Redactor(AbstractUser):
    years_of_experience = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Topic(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Newspaper(models.Model):
    title = models.CharField(max_length=64, unique=True)
    content = models.TextField()
    publish_date = models.DateTimeField()
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="newspapers"
    )
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title


class Commentary(models.Model):
    created_time = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    newspaper = models.ForeignKey(
        Newspaper, on_delete=models.CASCADE, related_name="comments"
    )

    class Meta:
        verbose_name_plural = "comments"

    def __str__(self):
        return f"{self.content}"

agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from agency.models import Newspaper, Redactor, Topic, Commentary


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = "__all__"


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=64,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"}),
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=64,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ("content",)


class RedactorYearsUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["years_of_experience"]

agency/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from agency.forms import (
    NewspaperForm,
    NewspaperSearchForm,
    TopicForm,
    RedactorCreationForm,
    RedactorSearchForm,
    CommentForm,
    RedactorYearsUpdateForm,
)
from agency.models import Newspaper, Topic, Redactor, Commentary


def index(request: HttpRequest) -> HttpResponse:
    newspapers_list = Newspaper.objects.select_related("topic").order_by("publish_date")
    topics_list = Topic.objects.all()

    return render(
        request,
        "agency/index.html",
        context={
            "newspapers_list": newspapers_list,
            "topics_list": topics_list,
        },
    )


class NewspaperListView(generic.ListView):
    model = Newspaper
    paginate_by = 5
    queryset = Newspaper.objects.all().order_by("publish_date")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["title"] = title
        context["search_form"] = NewspaperSearchForm(initial={"title": title})
        return context

    def get_queryset(self):
        form = NewspaperSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(title__icontains=form.cleaned_data["title"])
        return self.queryset


def newspaper_detail_view(request: HttpRequest, pk) -> HttpResponse:
    newspaper = Newspaper.objects.get(id=pk)

    if request.method == "GET":
        form = CommentForm(initial={"user": request.user})
        context = {"form": form, "newspaper": newspaper}
        return render(request, "agency/newspaper_detail.html", context=context)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if request.user.is_anonymous:
            form.add_error("content", "Please log in to add a comment")
        elif form.is_valid():
            Commentary.objects.create(
                user=request.user, newspaper=newspaper, **form.cleaned_data
            )
            return HttpResponseRedirect(
                reverse("agency:newspaper-detail", kwargs={"pk": pk})
            )

        context = {"form": form, "newspaper": newspaper}

        return render(request, "agency/newspaper_detail.html", context=context)


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("agency:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("agency:newspaper-list")


class TopicDetailView(generic.DetailView):
    model = Topic


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    form_class = TopicForm
    success_url = reverse_lazy("agency:index")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("agency:index")


class RedactorListView(generic.ListView):
    model = Redactor
    queryset = Redactor.objects.all()
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["username"] = username
        context["search_form"] = RedactorSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return self.queryset


def redactor_detail_view(request: HttpRequest, pk: int) -> render:
    redactor = Redactor.objects.filter(id=pk).first()

    if redactor:
        newspapers_list = redactor.newspapers.all()
        paginator = Paginator(newspapers_list, 3)

        page_number = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_number)
        context = {
            "redactor": redactor,
            "newspapers_page": page_obj,
        }

        return render(request, "agency/redactor_detail.html", context=context)
    else:
        return render(request, "agency/redactor_list.html")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("agency:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorYearsUpdateForm
    success_url = reverse_lazy("agency:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("agency:redactor-list")

templates/agency/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="banner text-center">
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <h1 class="mb-5">What Would You <br> Like To Read Today?</h1>
        <ul class="list-inline widget-list-inline">
          {% for topic in topics_list %}
            <li class="list-inline-item"><a href="{% url "agency:topic-detail" pk=topic.id %}">{{ topic.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

templates/agency/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="py-4">
    <section class="section">
      <div class="container">
         <div class="row justify-content-center">
            <div class=" col-lg-9   mb-5 mb-lg-0">
                <h1>Delete Newspaper {{ newspaper.title }}?</h1>
                <form action="" method="post" class="mt-5">
                  {% csrf_token %}
                    <a href="{% url 'agency:newspaper-detail' pk=newspaper.id%}" type="submit" class="btn btn-primary"> Cancel </a>
                    <input type="submit" value="Confirm" class="btn btn-danger">
                </form>
            </div>
         </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/agency/newspaper_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}

<div class="py-4"></div>
<section class="section">
  <div class="container">
    <div class="row justify-content-center">
      <div class=" col-lg-9   mb-5 mb-lg-0">
        <article>
          <h1 class="h2"> {{ newspaper.title }}</h1>
            {% if user.is_authenticated %}
            <a href="{% url 'agency:newspaper-delete' pk=newspaper.id %}"
               class="btn btn-primary link-to-page" style="background-color: red; border-color: red">
                Delete
            </a>
            <a href="{% url 'agency:newspaper-update' pk=newspaper.id %}"
               class="btn btn-primary link-to-page">
                Update
            </a>
            {% endif %}

        <div class="post-slider slider-sm">
            <img src="{% static 'images/default-article-img.png' %}" class="card-img-top" alt="post-img">
          </div>
          <ul class="card-meta my-3 list-inline">
            <li class="list-inline-item">
              <a href="author-single.html" class="card-meta-author">
                {% for publisher in newspaper.publishers.all %}
                <span> <a style="color: #777" href="{% url "agency:redactor-detail" pk=publisher.id %}"> {{ publisher.first_name }} {{ publisher.last_name }} |</a> </span>
                {% endfor %}
              </a>
            </li>
            <li class="list-inline-item">
              <i class="ti-timer"></i>2 Min To Read
            </li>
            <li class="list-inline-item">
              <i class="ti-calendar"></i> {{ newspaper.publish_date }}
            </li>
            <li class="list-inline-item">
              <ul class="card-meta-tag list-inline">
                <li class="list-inline-item"><a href="{% url "agency:topic-detail" pk=newspaper.topic.id %}">{{ newspaper.topic.name }}</a></li>
              </ul>
            </li>
          </ul>
          <div class="content">
            {{ newspaper.content }}
          </div>
        </article>

      </div>

      <div class="col-lg-9 col-md-12 mt-5">
      <span> <strong> {{ newspaper.comments.count }} comment{{ newspaper.comments.count|pluralize }}</strong> </span>
        {% if newspaper.comments.count %}
          {% for comment in newspaper.comments.all %}
            <ul class="list-group mt-2">
              <li class="list-group-item">
                <p style="font-weight: bold">{{ comment.user.first_name }} {{ comment.user.last_name }}</p>
                <p> {{ comment.content}}</p>
                <span class="text-muted"> {{ comment.created_time }}</span>
              </li>
            </ul>
          {% endfor %}
        {% else %}
          <p>No comments</p>
        {% endif %}
        <h3 class="mt-5">Add a comment</h3>
        <form action="" method="post" novalidate>
          <div class="form-group">
            {% csrf_token %}
            {{ form }}
          </div>
          <input type="submit" value="Comment" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/agency/newspaper_form.html
{% extends 'base.html' %}
{% block content %}
  <div class="py-4">
    <section class="section">
      <div class="container">
         <div class="row justify-content-center">
            <div class=" col-lg-9   mb-5 mb-lg-0">
              <h1>{{ object|yesno:"Update,Create" }} Newspaper </h1>
            <form action="" method="post" novalidate>
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Submit" class="btn btn-primary">
            </form>
            </div>
         </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/agency/newspaper_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
  <br>
  <section class="section-sm">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 mb-lg-0">
<h2 class="h5 section-title">Recent Newspapers {% if user.is_authenticated %}<a href="{% url 'agency:newspaper-create' %}" class="btn btn-primary link-to-page">
        Create
      </a> {% endif %}</h2>
   <form method="get" action="" class="widget-search">
    {{ search_form.as_p }}
    <input type="submit" value="🔍">
  </form>
  {% for newspaper in newspaper_list %}
  <article class="card mb-4">

  <div class="card-body">
      <h3 class="mb-3"><a class="post-title" href="{% url "agency:newspaper-detail" pk=newspaper.id %} ">{{ newspaper.title }}</a></h3>
      <ul class="card-meta list-inline">

          <li class="list-inline-item">
              <a href="" class="card-meta-author">
                {% for publisher in newspaper.publishers.all %}
                   <span> <a style="color: #777" href="{% url "agency:redactor-detail" pk=publisher.id %}"> {{ publisher.first_name }} |
                   </a></span>
                  {% endfor %}
              </a>
          </li>
          <li class="list-inline-item">
              <i class="ti-timer"></i>3 Min To Read
          </li>
          <li class="list-inline-item">
              <i class="ti-calendar"></i>{{ newspaper.publish_date}}
          </li>

      <li class="list-inline-item">
          <ul class="card-meta-tag list-inline">
          <li class="list-inline-item"><a href="{% url "agency:topic-detail" pk=newspaper.topic.id %}">{{ newspaper.topic }}</a></li>
          </ul>
      </li>
      </ul>
      <p>{{ newspaper.content|first_two_sentences }}</p>
      <a href="{% url "agency:newspaper-detail" pk=newspaper.id %}" class="btn btn-outline-primary">Read More</a>
  </div>
  </article>
  {% endfor %}
</div>
    </div>
  </div>
</section>
{% endblock %}

templates/agency/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="py-4">
    <section class="section">
      <div class="container">
         <div class="row justify-content-center">
            <div class=" col-lg-9   mb-5 mb-lg-0">
                <h1>Delete Redactor {{ redactor.first_name }} {{ redactor.last_name }}?</h1>
                <form action="" method="post" class="mt-5">
                  {% csrf_token %}
                    <a href="{% url 'agency:redactor-detail' pk=redactor.id%}" type="submit" class="btn btn-primary"> Cancel </a>
                    <input type="submit" value="Confirm" class="btn btn-danger">
                </form>
            </div>
         </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/agency/redactor_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section class="section-sm mt-5">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-lg-5 col-md-6 mb-4 mb-md-0">
          <div class="image-wrapper">
            <img class="img-fluid w-100" src="{% static 'images/default-profile-photo.jpeg' %}">
          </div>
        </div>
        <div class="col-lg-5 col-md-6">
          <div class="content pl-lg-3 pl-0">
            <h2>
              Hello I’m {{ redactor.first_name }} {{ redactor.last_name }}!</h2>
            {{ redactor.years_of_experience}} year{{ redactor.years_of_experience|pluralize }} of experience
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit massa vitae felis augue. In venenatis scelerisque accumsan egestas mattis. Massa feugiat in sem pellentesque.</p>
              {% if user.is_authenticated %}
            <a href="{% url 'agency:redactor-update' pk=redactor.id %}"
                   class="btn btn-primary link-to-page" style="color: white">
                    Update
                </a>
                <a href="{% url 'agency:redactor-delete' pk=redactor.id %}"
                 class="btn btn-primary link-to-page" style="background-color: red; border-color: red; color: white">
                  Delete
                </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="section-sm">
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        {% if newspapers_page %}
        <h2 class="mb-5">My newspapers</h2>
      </div>
      {% for newspaper in newspapers_page %}
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card border-0 rounded-0 text-center shadow-none overflow-hidden">
          <a href="#">
             <div class="book-cover">
              <img src="{% static 'images/default-article-img.png' %}" alt="" class="card-img-top rounded-0">
             </div>
             <div class="card-body">
                <h4 class="text-uppercase mb-3 "> <a class="post-title" href="{% url "agency:newspaper-detail" pk=newspaper.id %}">{{ newspaper.title }}</a></h4>
                <li class="list-inline-item">
                    <ul class="card-meta-tag list-inline">
                    <li class="list-inline-item"><a href="{% url "agency:topic-detail" pk=newspaper.topic.id %}">{{ newspaper.topic }}</a></li>
                    </ul>
                </li>
             </div>
           </a>
        </div>
     </div>
      {% endfor %}

    </div>
  </div>
</section>

<ul class="pagination justify-content-center mb-5">
{% if newspapers_page.has_previous %}
  <li class="page-item"><a class="page-link" href="?page={{ newspapers_page.previous_page_number }}"> Prev </a> </li>
{% endif %}
<li class="page-item page-item active" ><span class="page-link">{{ newspapers_page.number }}</span></li>
{% if newspapers_page.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ newspapers_page.next_page_number }}"> Next </a> </li>
{% endif %}
</ul>
{% else %}
  <h2 class="mb-5">No newspapers yet</h2>
{% endif %}
{% endblock %}

templates/agency/redactor_form.html
{% extends "base.html" %}
{% block content %}
    <div class="py-4">
    <section class="section">
      <div class="container">
         <div class="row justify-content-center">
            <div class=" col-lg-9   mb-5 mb-lg-0">
              <h1>{{ object|yesno:"Update,Create" }} Redactor </h1>
            <form action="" method="post" novalidate class="widget-search">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Submit" class="btn btn-outline-primary">
            </form>
            </div>
         </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/agency/redactor_list.html
{% extends "base.html" %}
{% block content %}
  <section class="section-sm">
  <div class="container">
  <h2 class="h5 section-title mt-5"> Our Redactors
    {% if user.is_authenticated %}
    <a href="{% url 'agency:redactor-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    {% endif %}
  </h2>
  <form method="get" action="" class="widget-search">
    {{ search_form.as_p }}
    <input type="submit" value="🔍">
  </form>
    <div class="row">
        {% for redactor in redactor_list %}
      <div class="col-sm-4">
        <div class="author-card text-center">
          <img class="author-image" src="https://onlineprofilepros.com/wp-content/uploads/2017/12/profile-photo.jpeg">
          <h3 class="mb-2"><a href="{% url "agency:redactor-detail" pk=redactor.id %}" class="post-title">{{ redactor.first_name}} {{ redactor.last_name }}</a></h3>
          <p class="mb-3">{{ redactor.username }}</p>
          <a class="post-count" href=""><i class="ti-pencil-alt mr-2"></i><span class="text-primary">{{ redactor.newspapers.count }}</span> Post{{ redactor.newspapers.count|pluralize}} by this author</a>
        </div>
      </div>
        {% endfor %}
    </div>
  </div>
  </section>
{% endblock %}

templates/agency/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="py-4">
    <section class="section">
      <div class="container">
         <div class="row justify-content-center">
            <div class=" col-lg-9   mb-5 mb-lg-0">
                <h1>Delete Topic {{ topic.name }}?</h1>
                <form action="" method="post" class="mt-5">
                  {% csrf_token %}
                    <a href="{% url 'agency:topic-detail' pk=topic.id%}" type="submit" class="btn btn-primary"> Cancel </a>
                    <input type="submit" value="Confirm" class="btn btn-danger">
                </form>
            </div>
         </div>
      </div>
    </section>
  </div>
{% endblock %}

templates/agency/topic_detail.html
{% extends "base.html" %}
{% load custom_filters %}
{% block content %}
   <br>
  <section class="section-sm">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8  mb-5 mb-lg-0">
  <h2 class="h5 section-title">{{ topic.name}}
    {% if user.is_authenticated %}
      <a href="{% url 'agency:topic-create' %}" class="btn btn-primary link-to-page">
          Create
        </a>
        <a href="{% url 'agency:topic-delete' pk=topic.id %}"
             class="btn btn-primary link-to-page" style="background-color: red; border-color: red; color: white">
              Delete
        </a>
    {% endif %}
  </h2>

  {% for newspaper in topic.newspapers.all %}
  <article class="card mb-4">
  <div class="card-body">
      <h3 class="mb-3"><a class="post-title" href="{% url "agency:newspaper-detail" pk=newspaper.id %}">{{ newspaper.title }}</a></h3>
      <ul class="card-meta list-inline">
          <li class="list-inline-item">
                {% for publisher in newspaper.publishers.all %}
                  <span> <a href="{% url "agency:redactor-detail" pk=publisher.id %}" class="card-meta-author">{{ publisher.first_name }} |</a> </span>
                  {% endfor %}
          </li>
          <li class="list-inline-item">
              <i class="ti-timer"></i>3 Min To Read
          </li>
          <li class="list-inline-item">
              <i class="ti-calendar"></i>{{ newspaper.publish_date}}
          </li>
      <li class="list-inline-item">
          <ul class="card-meta-tag list-inline">
          <li class="list-inline-item"><a href="">{{ newspaper.topic }}</a></li>
          </ul>
      </li>
      </ul>
      <p>{{ newspaper.content|first_two_sentences }}</p>
      <a href="{% url "agency:newspaper-detail" pk=newspaper.id %}" class="btn btn-outline-primary">Read More</a>
  </div>
  </article>
  {% endfor %}
      </div>
    </div>
{% endblock %}
</div>
</section>

templates/agency/topic_form.html
{% extends "base.html" %}
{% block content %}
    <div class="py-4">
    <section class="section">
      <div class="container">
         <div class="row justify-content-center">
            <div class=" col-lg-9   mb-5 mb-lg-0">
              <h1>{{ object|yesno:"Update,Create" }} Topic </h1>
            <form action="" method="post" novalidate class="widget-search">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Submit" class="btn btn-outline-primary">
            </form>
            </div>
         </div>
      </div>
    </section>
  </div>
{% endblock %}