agency/urls.py
from django.urls import path

from agency.views import (
    index,
    NewspaperListView,
    NewspaperCreateView,
    TopicDetailView,
    TopicCreateView,
    TopicDeleteView,
    RedactorListView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    newspaper_detail_view,
    NewspaperDeleteView,
    NewspaperUpdateView,
    redactor_detail_view,
)

urlpatterns = [
    path("", index, name="index"),
    path("newspapers/", NewspaperListView.as_view(), name="newspaper-list"),
    path(
        "newspapers/<int:pk>/", newspaper_detail_view, name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path("topics/<int:pk>/", TopicDetailView.as_view(), name="topic-detail"),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path("redactors/", RedactorListView.as_view(), name="redactor-list"),
    path("redactors/<int:pk>/", redactor_detail_view, name="redactor-detail"),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create",
    ),
    path(
        "redactors/<int:pk>/update",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
]

app_name = "agency"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("agency.urls", namespace="agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/navbar.html
<header class="navigation fixed-top">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-white" style="background-color: white">
      <div class="collapse navbar-collapse text-center order-lg-2 order-3" id="navigation">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item dropdown">
            <a class="nav-link" href="{% url "agency:index" %}" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              homepage <i class="ti-angle-down ml-1"></i>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="{% url "agency:newspaper-list" %}" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              Newspapers <i class="ti-angle-down ml-1"></i>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url "agency:redactor-list" %}">Redactors</a>
          </li>
          <li class="nav-item">
          </li>
        </ul>
      </div>
      <div class="order-2 order-lg-3 d-flex align-items-center">
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-primary link-to-page"> Log out </a>
        {% else %}
          <a class="btn btn-primary link-to-page" href="{% url 'login'%}?next={{request.path}}">Log in</a>
        {% endif %}
      </div>
    </nav>
  </div>
</header>

templates/includes/pagination.html
{% if is_paginated %}
<ul class="pagination justify-content-center mb-5">
{% if page_obj.has_previous %}
  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"> Prev </a> </li>
{% endif %}
<li class="page-item page-item active" ><span class="page-link">{{ page_obj.number }}</span></li>
{% if page_obj.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"> Next </a> </li>
{% endif %}
</ul>
{% endif %}